# 服务端口
server:
  port: 8208

spring:
  # 服务名
  application:
    name: service-statistics
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  #nacos服务地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848