server:
  port: 80

spring:
  application:
    #nacos服务名
    name: service-geteway
  cloud:
    nacos:
      discovery:
        #nacos服务地址
        server-addr: 127.0.0.1
        port: 8848
    gateway:
      discovery:
        locator:
          #使用服务发现路由
          enabled: true
      routes:
        #设置路由id
        - id: service-hosp
          #设置路由uri
          uri: lb://service-hosp
          #设置路由断言
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
