server:
  port: 8204

spring:
  application:
    #nacos服务名
    name: service-msm
  profiles:
    active: dev
  cloud:
    nacos:
      #nacos服务地址
      server-addr: 127.0.0.1:8848
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1978512164@qq.com #QQ邮箱
    password: zsepxtxqwwwcdjeh #客户端授权码
    protocol: smtp #发送邮件协议
    default-encoding: utf-8
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
#rabbitmq地址
  rabbitmq:
    host: 81.71.71.98
    port: 5672
    username: guest
    password: guest

aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI5tJpWBRDmvJKKrxpQmRt
    secret: ggYsu4ewRNNUSFzbv4jf6i3wrrvSzJ

